# Generated by Django 5.0.3 on 2024-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_checkout_checkoutproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentstatus',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0),
        ),
    ]
