# Generated by Django 5.0.3 on 2024-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_contact_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
